import asyncio
import json
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.db.database import AsyncSessionLocal
from src.db.models import Product

SEED_PRODUCTS = [
    {
        "id": "prod_mooleh_manay_excelsa",
        "name": "Excelsa by Mooleh Manay Estate",
        "slug": "excelsa-by-mooleh-manay-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-EXCELSA-100",
        "category": "producer_series",
        "price": 600.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "NANO LOT",
        "rating": 5.0,
        "review_count": 28,
        "tax_category": "coffee_beans",
        "width_cm": 10.0,
        "height_cm": 18.0,
        "depth_cm": 5.0,
        "weight_kg": 0.10,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "light",
        "process_method": "carbonic_maceration",
        "estate_name": "Mooleh Manay Estate",
        "region": "Coorg, Karnataka",
        "elevation_m": 1100,
        "varietal": "Excelsa",
        "resting_period_days": 13,
        "acidity": "medium",
        "bitterness": "low",
        "body": "Medium to High",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/final.png?v=1788875724",
        "description": "Exploration beyond Arabica and Robusta with rare Excelsa cherries. 132-hour dual-phase fermentation with wine yeast and lactobacillus creates a creamy, fruit-forward mouthfeel.",
        "taste_notes": ["Wild Berries", "Red Plum", "Ripe Banana", "Nutmeg", "Sweet Cedar", "Malt"],
        "recommended_brew_methods": ["espresso", "pour_over", "french_press"],
        "variants": [
            {"size": "100g", "weight_grams": 100, "price": 600.00, "sku": "HJ-EXCELSA-100", "available": True}
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/final.png?v=1788875724"}
        ],
        "taste_notes_json": '["Wild Berries", "Red Plum", "Ripe Banana", "Nutmeg", "Sweet Cedar", "Malt"]',
        "specs_json": '{"Fermentation": "132h Carbonic Maceration", "Species": "Coffea Excelsa", "Drying": "12 Days Polyhouse"}',
    },
    {
        "id": "prod_baarbara_estate_whiskey_barrel",
        "name": "Baarbara Estate - Whiskey Barrel Aged",
        "slug": "baarbara-estate-whiskey-barrel",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-BAARBARA-WBA-250",
        "category": "single_origin",
        "price": 1250.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "EXCLUSIVE LOT",
        "rating": 5.0,
        "review_count": 64,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium",
        "process_method": "whiskey_barrel",
        "estate_name": "Baarbara Estate",
        "region": "Baba Budangiri, Karnataka",
        "elevation_m": 1450,
        "varietal": "Arabica Selection",
        "resting_period_days": 10,
        "acidity": "medium",
        "bitterness": "low",
        "body": "Layered and Complex",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1_6.jpg?v=1787560255",
        "description": "Aged for nearly four months in freshly emptied malt whiskey oak barrels in a controlled microclimate. Wine-like aromas with non-alcoholic whiskey oak and Irish cream finish.",
        "taste_notes": ["Red Plum", "Whiskey Oak", "Ripe Banana", "Cocoa", "Sweet Cardamom", "Irish Cream"],
        "recommended_brew_methods": ["espresso", "cold_brew", "pour_over", "aeropress"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 1250.00, "sku": "HJ-BAARBARA-WBA-250", "available": True}
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1_6.jpg?v=1787560255"}
        ],
        "taste_notes_json": '["Red Plum", "Whiskey Oak", "Ripe Banana", "Cocoa", "Sweet Cardamom", "Irish Cream"]',
        "specs_json": '{"Aging": "4 Months Oak Barrel", "Alcohol": "Non-Alcoholic", "Origin": "Foothills of Baba Budangiri"}',
    },
    {
        "id": "prod_riverdale_estate_mosto",
        "name": "Riverdale Estate - Mosto",
        "slug": "riverdale-estate-mosto",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-RIVERDALE-MOSTO-200",
        "category": "producer_series",
        "price": 1000.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "PRODUCER SERIES",
        "rating": 4.9,
        "review_count": 31,
        "tax_category": "coffee_beans",
        "width_cm": 11.0,
        "height_cm": 19.0,
        "depth_cm": 5.5,
        "weight_kg": 0.20,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "light",
        "process_method": "carbonic_maceration",
        "estate_name": "Riverdale Estate",
        "region": "Shevaroy Hills, Tamil Nadu",
        "elevation_m": 1500,
        "varietal": "SLN 9",
        "resting_period_days": 13,
        "acidity": "medium-high",
        "bitterness": "low",
        "body": "Silky Mouthfeel",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/PS-Mosto-list.png?v=1787554172",
        "description": "Fermented with microbe-rich Gesha Mosto liquid starter culture through a 72-hour controlled fermentation, followed by slow drying on raised beds for 30 days.",
        "taste_notes": ["Pink Pomelo", "Tart Cherries", "Chamomile", "Pomegranate", "Gooseberry"],
        "recommended_brew_methods": ["pour_over", "aeropress"],
        "variants": [
            {"size": "200g", "weight_grams": 200, "price": 1000.00, "sku": "HJ-RIVERDALE-MOSTO-200", "available": True}
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/PS-Mosto-list.png?v=1787554172"}
        ],
        "taste_notes_json": '["Pink Pomelo", "Tart Cherries", "Chamomile", "Pomegranate", "Gooseberry"]',
        "specs_json": '{"Starter": "Gesha Mosto Culture", "Drying": "30 Days Raised Beds", "Varietal": "SLN 9"}',
    },
    {
        "id": "prod_raxidi_lobo_pichia_yeast",
        "name": "Raxidi Lobo Estate - Pichia Yeast",
        "slug": "raxidi-lobo-estate-pichia-yeast",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-RAXIDI-PICHIA-200",
        "category": "producer_series",
        "price": 1000.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "PRODUCER SERIES",
        "rating": 4.9,
        "review_count": 22,
        "tax_category": "coffee_beans",
        "width_cm": 11.0,
        "height_cm": 19.0,
        "depth_cm": 5.5,
        "weight_kg": 0.20,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "light",
        "process_method": "anaerobic",
        "estate_name": "Raxidi Lobo Estate",
        "region": "Karnataka",
        "elevation_m": 1200,
        "varietal": "Arabica Selection",
        "resting_period_days": 13,
        "acidity": "medium-high",
        "bitterness": "low",
        "body": "Juicy and Expressive",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/PS-Listing_Web.png?v=1784289488",
        "description": "Selected ripe red cherries guided by a 48-hour stainless steel anaerobic fermentation with Pichia yeast strain, then slow dried on raised beds for 21 days.",
        "taste_notes": ["Strawberry Jam", "Raspberry", "Plum Tart", "Marigold", "Red Cherry", "Candied Orange Peel"],
        "recommended_brew_methods": ["pour_over", "aeropress"],
        "variants": [
            {"size": "200g", "weight_grams": 200, "price": 1000.00, "sku": "HJ-RAXIDI-PICHIA-200", "available": True}
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/PS-Listing_Web.png?v=1784289488"}
        ],
        "taste_notes_json": '["Strawberry Jam", "Raspberry", "Plum Tart", "Marigold", "Red Cherry", "Candied Orange Peel"]',
        "specs_json": '{"Fermentation": "48h Pichia Yeast Anaerobic", "Drying": "21 Days Raised Beds"}',
    },
    {
        "id": "prod_the_monsoon_trio",
        "name": "The Monsoon Trio (Discovery Pack)",
        "slug": "the-monsoon-trio",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-MONSOON-TRIO-225",
        "category": "sampler",
        "price": 600.00,
        "compare_at_price": 650.00,
        "status": "active",
        "in_stock": True,
        "badge": "DISCOVERY BOX",
        "rating": 4.8,
        "review_count": 89,
        "tax_category": "coffee_beans",
        "width_cm": 15.0,
        "height_cm": 22.0,
        "depth_cm": 7.0,
        "weight_kg": 0.225,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium_dark",
        "process_method": "monsooned",
        "estate_name": "Multi-Estate Assortment",
        "region": "Karnataka & Tamil Nadu",
        "elevation_m": 1300,
        "varietal": "Monsoon Malabar AA & Arabica Washed",
        "resting_period_days": 10,
        "acidity": "low",
        "bitterness": "medium",
        "body": "Full and Comforting",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/Card-01_a5dbef83-3fa2-4cf6-ba07-c0227a545720.jpg?v=1787035346",
        "description": "Curated trio bringing together comforting medium-dark roasts: Monsoon Malabar AA from Hoysala Estate, St. Joseph Estate washed, and Sampigehoney Estate.",
        "taste_notes": ["Cocoa Nibs", "Raisins", "Orange Marmalade", "Clove", "Toffee", "Dark Chocolate"],
        "recommended_brew_methods": ["french_press", "moka_pot", "espresso", "pour_over", "south_indian_filter"],
        "variants": [
            {"size": "3 x 75g (225g)", "weight_grams": 225, "price": 600.00, "compare_at_price": 650.00, "sku": "HJ-MONSOON-TRIO-225", "available": True}
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/Card-01_a5dbef83-3fa2-4cf6-ba07-c0227a545720.jpg?v=1787035346"}
        ],
        "taste_notes_json": '["Cocoa Nibs", "Raisins", "Orange Marmalade", "Clove", "Toffee", "Dark Chocolate"]',
        "specs_json": '{"Lots": "Hoysala Monsoon Malabar, St. Joseph, Sampigehoney", "Pack": "3 x 75g"}',
    },
    {
        "id": "prod_sampigehoney_estate",
        "name": "Sampigehoney Estate",
        "slug": "sampigehoney-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-SAMPIGE-250",
        "category": "single_origin",
        "price": 700.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "SEASONAL ROSTER",
        "rating": 4.9,
        "review_count": 115,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium_dark",
        "process_method": "washed",
        "estate_name": "Sampigehoney Estate",
        "region": "Chikmagalur, Karnataka",
        "elevation_m": 1250,
        "varietal": "Arabica Washed",
        "resting_period_days": 9,
        "acidity": "medium",
        "bitterness": "medium",
        "body": "Syrupy and Medium-High",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Sampigehoney-Estate-_Front_dc9733a5-f382-4f6e-a2fa-a04081f2457a.jpg?v=1786096950",
        "description": "Comforting washed coffee from Chikmagalur with aromas of honey and raisins, delivering layers of zesty orange marmalade and rich dark chocolate finish.",
        "taste_notes": ["Orange Marmalade", "Dark Chocolate", "Honey", "Sweet Raisins"],
        "recommended_brew_methods": ["espresso", "french_press", "moka_pot"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 700.00, "sku": "HJ-SAMPIGE-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1300.00, "sku": "HJ-SAMPIGE-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2380.00, "sku": "HJ-SAMPIGE-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Sampigehoney-Estate-_Front_dc9733a5-f382-4f6e-a2fa-a04081f2457a.jpg?v=1786096950"}
        ],
        "taste_notes_json": '["Orange Marmalade", "Dark Chocolate", "Honey", "Sweet Raisins"]',
        "specs_json": '{"Process": "Washed", "Region": "Chikmagalur", "Roast": "Medium-Dark"}',
    },
    {
        "id": "prod_unakki_estate",
        "name": "Unakki Estate",
        "slug": "unakki-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-UNAKKI-250",
        "category": "single_origin",
        "price": 800.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "HARVEST '26",
        "rating": 4.9,
        "review_count": 78,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium",
        "process_method": "washed",
        "estate_name": "Unakki Estate",
        "region": "Joldal Palya, Chikmagalur, Karnataka",
        "elevation_m": 1200,
        "varietal": "Arabica Washed",
        "resting_period_days": 10,
        "acidity": "medium",
        "bitterness": "medium",
        "body": "Syrupy Mouthfeel with Tea-like Finish",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Unakki-Estate__Front.jpg?v=1786091498",
        "description": "Grown in the lush forests of Joldal Palya in Chikmagalur. Honey aroma leading into chocolate, brown spices, and raisins with a refined tea-like finish.",
        "taste_notes": ["Chocolate", "Brown Spices", "Sweet Honey", "Raisins"],
        "recommended_brew_methods": ["espresso", "pour_over", "moka_pot", "aeropress"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 800.00, "sku": "HJ-UNAKKI-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1488.00, "sku": "HJ-UNAKKI-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2720.00, "sku": "HJ-UNAKKI-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Unakki-Estate__Front.jpg?v=1786091498"}
        ],
        "taste_notes_json": '["Chocolate", "Brown Spices", "Sweet Honey", "Raisins"]',
        "specs_json": '{"Terroir": "Forest Shade Grown", "Process": "Washed", "Finish": "Tea-like"}',
    },
    {
        "id": "prod_ms_estate",
        "name": "M.S. Estate",
        "slug": "ms-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-MS-250",
        "category": "single_origin",
        "price": 800.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "PERENNIAL FAVORITE",
        "rating": 5.0,
        "review_count": 184,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium",
        "process_method": "washed",
        "estate_name": "M.S. Estate",
        "region": "Chikmagalur, Karnataka",
        "elevation_m": 1350,
        "varietal": "S795 & Rare Ethiopian Varietal",
        "resting_period_days": 8,
        "acidity": "medium",
        "bitterness": "low",
        "body": "Chocolatey with Distinct Tea Finish",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-M.S.-Estate__Front.jpg?v=1784120116",
        "description": "Cultivating a rare Ethiopian heirloom varietal alongside S795 in Chikmagalur since the late 1990s. Aromas of dried apricots and peaches leading to a lingering chocolate finish.",
        "taste_notes": ["Dried Apricots", "Peaches", "Chocolate Essence", "Black Tea"],
        "recommended_brew_methods": ["espresso", "pour_over", "aeropress", "moka_pot"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 800.00, "sku": "HJ-MS-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1488.00, "sku": "HJ-MS-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2720.00, "sku": "HJ-MS-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-M.S.-Estate__Front.jpg?v=1784120116"}
        ],
        "taste_notes_json": '["Dried Apricots", "Peaches", "Chocolate Essence", "Black Tea"]',
        "specs_json": '{"Varietal": "S795 & Historic Ethiopian Heirloom", "Process": "Washed"}',
    },
    {
        "id": "prod_krishnagiri_estate",
        "name": "Krishnagiri Estate",
        "slug": "krishnagiri-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-KRISHNAGIRI-250",
        "category": "single_origin",
        "price": 700.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "RAINFOREST ALLIANCE",
        "rating": 4.8,
        "review_count": 92,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "dark",
        "process_method": "washed",
        "estate_name": "Krishnagiri Estate",
        "region": "Karnataka",
        "elevation_m": 1200,
        "varietal": "Arabica Washed",
        "resting_period_days": 7,
        "acidity": "low",
        "bitterness": "medium-high",
        "body": "Heavy Velvety Body",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Krishnagiri-Estate__Front.jpg?v=1784120117",
        "description": "Rainforest Alliance-certified farm using custom-designed eco-pulpers to conserve water. A deep dark roast with brown spice aromatics, oak, toasted walnuts, and malt finish.",
        "taste_notes": ["Brown Spices", "Oak", "Toasted Walnuts", "Malt", "Bittersweet Cocoa"],
        "recommended_brew_methods": ["espresso", "moka_pot", "french_press", "aeropress"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 700.00, "sku": "HJ-KRISHNAGIRI-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1300.00, "sku": "HJ-KRISHNAGIRI-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2380.00, "sku": "HJ-KRISHNAGIRI-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Krishnagiri-Estate__Front.jpg?v=1784120117"}
        ],
        "taste_notes_json": '["Brown Spices", "Oak", "Toasted Walnuts", "Malt", "Bittersweet Cocoa"]',
        "specs_json": '{"Certification": "Rainforest Alliance", "Roast": "Dark", "Process": "Eco-Washed"}',
    },
    {
        "id": "prod_salawara_estate",
        "name": "Salawara Estate",
        "slug": "salawara-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-SALAWARA-250",
        "category": "single_origin",
        "price": 850.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "HARVEST '26",
        "rating": 5.0,
        "review_count": 45,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "light",
        "process_method": "anaerobic",
        "estate_name": "Salawara Estate",
        "region": "Chikmagalur, Karnataka",
        "elevation_m": 1250,
        "varietal": "Arabica Anaerobic Natural",
        "resting_period_days": 12,
        "acidity": "medium-high",
        "bitterness": "low",
        "body": "Well-Rounded and Juicy",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Salawara-Estate__Front_8b9bc3a2-4cc5-48d6-b256-ec2549e4558e.jpg?v=1784115306",
        "description": "Crafted by third-generation producer Sharan in Chikmagalur. Anaerobic natural lot delivering a burst of fruit: pineapple, molasses on the nose, settling into crisp red apple and almond.",
        "taste_notes": ["Pineapple", "Molasses", "Red Apple", "Pear", "Roasted Almond"],
        "recommended_brew_methods": ["pour_over", "aeropress"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 850.00, "sku": "HJ-SALAWARA-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1580.00, "sku": "HJ-SALAWARA-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2890.00, "sku": "HJ-SALAWARA-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Salawara-Estate__Front_8b9bc3a2-4cc5-48d6-b256-ec2549e4558e.jpg?v=1784115306"}
        ],
        "taste_notes_json": '["Pineapple", "Molasses", "Red Apple", "Pear", "Roasted Almond"]',
        "specs_json": '{"Producer": "Sharan", "Process": "Anaerobic Natural", "Roast": "Light"}',
    },
    {
        "id": "prod_kerehaklu_blossom_culture",
        "name": "Kerehaklu Estate - Blossom Culture",
        "slug": "kerehaklu-estate-blossom-culture",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-KEREHAKLU-BC-200",
        "category": "producer_series",
        "price": 1000.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "PRODUCER SERIES",
        "rating": 5.0,
        "review_count": 36,
        "tax_category": "coffee_beans",
        "width_cm": 11.0,
        "height_cm": 19.0,
        "depth_cm": 5.5,
        "weight_kg": 0.20,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "light",
        "process_method": "anaerobic",
        "estate_name": "Kerehaklu Estate",
        "region": "Chikmagalur, Karnataka",
        "elevation_m": 1300,
        "varietal": "Arabica Blossom Fermentation",
        "resting_period_days": 12,
        "acidity": "medium-high",
        "bitterness": "low",
        "body": "Distinctive Jamminess",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/finalproductimgs.png?v=1782896537",
        "description": "Wild blossoms collected from the fog-shrouded block to create a starter culture for 71-hour anoxic fermentation. Jammy ripe berries, orange blossom, and sun melon.",
        "taste_notes": ["Ripe Berries", "Strawberry", "Orange Blossom", "Pomegranate", "Sun Melon"],
        "recommended_brew_methods": ["pour_over", "aeropress"],
        "variants": [
            {"size": "200g", "weight_grams": 200, "price": 1000.00, "sku": "HJ-KEREHAKLU-BC-200", "available": True}
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/finalproductimgs.png?v=1782896537"}
        ],
        "taste_notes_json": '["Ripe Berries", "Strawberry", "Orange Blossom", "Pomegranate", "Sun Melon"]',
        "specs_json": '{"Fermentation": "71h Anoxic Blossom Culture", "Drying": "3 Weeks Raised Beds"}',
    },
    {
        "id": "prod_attikan_estate",
        "name": "Attikan Estate",
        "slug": "attikan-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-ATTIKAN-250",
        "category": "single_origin",
        "price": 700.00,
        "compare_at_price": 700.00,
        "status": "active",
        "in_stock": True,
        "badge": "BESTSELLER",
        "rating": 5.0,
        "review_count": 420,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium_dark",
        "process_method": "washed",
        "estate_name": "Attikan Estate",
        "region": "Biligiriranga Hills, Karnataka",
        "elevation_m": 1650,
        "varietal": "Selection 9, S795, Cauvery, Kent",
        "resting_period_days": 10,
        "acidity": "medium",
        "bitterness": "medium-high",
        "body": "Heavy and Velvety",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/Attikan-estate-Front.jpg?v=1734956514",
        "description": "Grown in the cloud-draped Biligiriranga Hills at 1650 meters, amongst the highest coffee elevations in India. Sweet with nutty overtones, balanced acidity, and rich dark chocolate crema.",
        "taste_notes": ["Dark Chocolate", "Roasted Almonds", "Sweet Fig", "Nutty"],
        "recommended_brew_methods": ["espresso", "moka_pot", "south_indian_filter", "aeropress", "french_press"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 700.00, "sku": "HJ-ATTIKAN-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1300.00, "sku": "HJ-ATTIKAN-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2380.00, "sku": "HJ-ATTIKAN-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/Attikan-estate-Front.jpg?v=1734956514"}
        ],
        "taste_notes_json": '["Dark Chocolate", "Roasted Almonds", "Sweet Fig", "Nutty"]',
        "specs_json": '{"Elevation": "1650m MSL", "Region": "Biligiriranga Hills", "Roast": "Medium-Dark"}',
    },
    {
        "id": "prod_13th_birthday_blend",
        "name": "13th Birthday Blend",
        "slug": "13th-birthday-blend",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-13BDAY-250",
        "category": "blend",
        "price": 800.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "LIMITED RELEASE",
        "rating": 4.9,
        "review_count": 52,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium",
        "process_method": "natural",
        "estate_name": "Stanmore, Orchardale, Riverdale & Unakki",
        "region": "Yercaud & Chikmagalur",
        "elevation_m": 1400,
        "varietal": "Multi-Estate Blend",
        "resting_period_days": 10,
        "acidity": "medium",
        "bitterness": "low",
        "body": "Medium-High Round Body",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/Card_01_1_c34d4c4f-016a-4780-af62-97ce1a125f21.jpg?v=1767077475",
        "description": "Celebratory anniversary blend reminiscent of classic Black Forest cake. Natural lots from Yercaud paired with a washed base from Unakki Estate. Chocolate-covered strawberries finish.",
        "taste_notes": ["Strawberry", "Dark Chocolate", "Black Forest Cherry", "Pear"],
        "recommended_brew_methods": ["espresso", "aeropress", "french_press", "moka_pot", "pour_over"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 800.00, "sku": "HJ-13BDAY-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1488.00, "sku": "HJ-13BDAY-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2720.00, "sku": "HJ-13BDAY-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/Card_01_1_c34d4c4f-016a-4780-af62-97ce1a125f21.jpg?v=1767077475"}
        ],
        "taste_notes_json": '["Strawberry", "Dark Chocolate", "Black Forest Cherry", "Pear"]',
        "specs_json": '{"Profile": "Black Forest Cake", "Blend": "Naturals (Yercaud) + Washed (Chikmagalur)"}',
    },
    {
        "id": "prod_howdia_estate",
        "name": "Howdia Estate",
        "slug": "howdia-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-HOWDIA-250",
        "category": "single_origin",
        "price": 850.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "ROASTER FAVORITE",
        "rating": 4.9,
        "review_count": 67,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "light",
        "process_method": "washed",
        "estate_name": "Howdia Estate",
        "region": "Pulney Hills, Tamil Nadu",
        "elevation_m": 1400,
        "varietal": "Arabica Washed",
        "resting_period_days": 10,
        "acidity": "medium",
        "bitterness": "low",
        "body": "Well-Rounded and Floral",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Howdia-Estate__Front.jpg?v=1782107101",
        "description": "Among our most delicate light roasts, reminiscent of a floral black tea. Bright acidity, orange marmalade notes, and a clean tea-like finish.",
        "taste_notes": ["Coffee Blossoms", "Orange Marmalade", "Floral Black Tea"],
        "recommended_brew_methods": ["pour_over", "aeropress"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 850.00, "sku": "HJ-HOWDIA-250", "available": True}
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Howdia-Estate__Front.jpg?v=1782107101"}
        ],
        "taste_notes_json": '["Coffee Blossoms", "Orange Marmalade", "Floral Black Tea"]',
        "specs_json": '{"Terroir": "Pulney Hills", "Roast": "Light", "Profile": "Tea-like Florality"}',
    },
    {
        "id": "prod_st_joseph_estate",
        "name": "St. Joseph Estate",
        "slug": "st-joseph-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-STJOSEPH-250",
        "category": "single_origin",
        "price": 700.00,
        "compare_at_price": 700.00,
        "status": "active",
        "in_stock": True,
        "badge": "PARTNER FARM",
        "rating": 4.8,
        "review_count": 73,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium_dark",
        "process_method": "washed",
        "estate_name": "St. Joseph Estate",
        "region": "Tamil Nadu",
        "elevation_m": 1300,
        "varietal": "Arabica Washed",
        "resting_period_days": 11,
        "acidity": "medium",
        "bitterness": "medium-high",
        "body": "Medium-High Syrupy Body",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-St.Joseph-Estate__Front_2.jpg?v=1764321548",
        "description": "Cultivated by a community of Jesuit priests with generations of stewardship. Warm brown spices, roasted almonds, grapefruit, and comforting toffee finish.",
        "taste_notes": ["Grapefruit", "Roasted Almond", "Toffee", "Warm Brown Spices"],
        "recommended_brew_methods": ["espresso", "aeropress", "moka_pot", "french_press"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 700.00, "sku": "HJ-STJOSEPH-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1300.00, "sku": "HJ-STJOSEPH-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2380.00, "sku": "HJ-STJOSEPH-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-St.Joseph-Estate__Front_2.jpg?v=1764321548"}
        ],
        "taste_notes_json": '["Grapefruit", "Roasted Almond", "Toffee", "Warm Brown Spices"]',
        "specs_json": '{"Stewardship": "Jesuit Priests Community", "Roast": "Medium-Dark"}',
    },
    {
        "id": "prod_raxidi_lobo_anaerobic_natural",
        "name": "Raxidi Lobo Estate - Anaerobic Natural",
        "slug": "raxidi-lobo-estate-anaerobic-natural",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-RAXIDI-AN-250",
        "category": "single_origin",
        "price": 900.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "LIMITED RELEASE",
        "rating": 5.0,
        "review_count": 39,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium",
        "process_method": "anaerobic",
        "estate_name": "Raxidi Lobo Estate",
        "region": "Karnataka",
        "elevation_m": 1200,
        "varietal": "Arabica Anaerobic Natural",
        "resting_period_days": 11,
        "acidity": "medium-high",
        "bitterness": "low",
        "body": "Velvety Medium Body",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Raxidi-Lobo-Estate__Front_1f24d4f9-58d2-45c0-8266-c3767720de8d.jpg?v=1777466382",
        "description": "Carries the sweet nostalgia of drinking fresh mosambi juice in summer. Berries on the nose, settling into bright tart-sweet notes of green apple and plum.",
        "taste_notes": ["Fresh Mosambi Juice", "Green Apple", "Summer Berries", "Plum"],
        "recommended_brew_methods": ["pour_over", "aeropress"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 900.00, "sku": "HJ-RAXIDI-AN-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1675.00, "sku": "HJ-RAXIDI-AN-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 3060.00, "sku": "HJ-RAXIDI-AN-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Raxidi-Lobo-Estate__Front_1f24d4f9-58d2-45c0-8266-c3767720de8d.jpg?v=1777466382"}
        ],
        "taste_notes_json": '["Fresh Mosambi Juice", "Green Apple", "Summer Berries", "Plum"]',
        "specs_json": '{"Fermentation": "48h Curated Yeast", "Drying": "21 Days Raised Beds"}',
    },
    {
        "id": "prod_kerehaklu_estate_light",
        "name": "Kerehaklu Estate (Light Roast)",
        "slug": "kerehaklu-estate-light",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-KEREHAKLU-LT-250",
        "category": "single_origin",
        "price": 850.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "HARVEST '26",
        "rating": 5.0,
        "review_count": 88,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "light",
        "process_method": "washed",
        "estate_name": "Kerehaklu Estate",
        "region": "Chikmagalur, Karnataka",
        "elevation_m": 1300,
        "varietal": "Selection 9",
        "resting_period_days": 12,
        "acidity": "medium-high",
        "bitterness": "low",
        "body": "Juicy Mouthfeel",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Kerehaklu-Estate__Front.jpg?v=1775204109",
        "description": "Bright, citrusy light roast. Ripe Selection 9 cherries fermented with farm's local starter microbes for 37 hours, shade dried, then finished in polyhouses.",
        "taste_notes": ["Orange Blossoms", "Brown Sugar", "Green Grapes", "Orange Marmalade"],
        "recommended_brew_methods": ["pour_over", "aeropress"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 850.00, "sku": "HJ-KEREHAKLU-LT-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1580.00, "sku": "HJ-KEREHAKLU-LT-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2890.00, "sku": "HJ-KEREHAKLU-LT-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/1.-Kerehaklu-Estate__Front.jpg?v=1775204109"}
        ],
        "taste_notes_json": '["Orange Blossoms", "Brown Sugar", "Green Grapes", "Orange Marmalade"]',
        "specs_json": '{"Producers": "Pranoy & Ajoy", "Process": "Aerobic Washed", "Varietal": "Selection 9"}',
    },
    {
        "id": "prod_sandalwood_estate",
        "name": "Sandalwood Estate",
        "slug": "sandalwood-estate",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-SANDALWOOD-250",
        "category": "single_origin",
        "price": 750.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "PERENNIAL ROSTER",
        "rating": 4.9,
        "review_count": 134,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium_dark",
        "process_method": "washed",
        "estate_name": "Sandalwood Estate",
        "region": "Coorg, Karnataka",
        "elevation_m": 1200,
        "varietal": "Sarchimor",
        "resting_period_days": 11,
        "acidity": "medium",
        "bitterness": "medium",
        "body": "Heavy Syrupy Body",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/Sandalwood-Estate-Front.jpg?v=1734957649",
        "description": "Washed coffee of the resilient Sarchimor varietal grown in lush Coorg. Tasting notes of rich dark chocolate, sweet prune, and lingering butter biscuits aftertaste.",
        "taste_notes": ["Rich Dark Chocolate", "Sweet Prune", "Orange Marmalade", "Butter Biscuits"],
        "recommended_brew_methods": ["espresso", "moka_pot", "french_press"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 750.00, "sku": "HJ-SANDALWOOD-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1395.00, "sku": "HJ-SANDALWOOD-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2550.00, "sku": "HJ-SANDALWOOD-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/Sandalwood-Estate-Front.jpg?v=1734957649"}
        ],
        "taste_notes_json": '["Rich Dark Chocolate", "Sweet Prune", "Orange Marmalade", "Butter Biscuits"]',
        "specs_json": '{"Varietal": "Sarchimor", "Region": "Coorg", "Roast": "Medium-Dark"}',
    },
    {
        "id": "prod_dhak_blend",
        "name": "Dhak Blend",
        "slug": "dhak-blend",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-DHAK-250",
        "category": "blend",
        "price": 700.00,
        "compare_at_price": 650.00,
        "status": "active",
        "in_stock": True,
        "badge": "BESTSELLER",
        "rating": 5.0,
        "review_count": 312,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "dark",
        "process_method": "natural",
        "estate_name": "Chikmagalur Naturals",
        "region": "Chikmagalur, Karnataka",
        "elevation_m": 1200,
        "varietal": "Natural Process Blend",
        "resting_period_days": 9,
        "acidity": "low",
        "bitterness": "medium-high",
        "body": "Heavy Cocoa Body",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/Dhak-Blend-Front.jpg?v=1734947063",
        "description": "Ode to the flame of the forest tree. Naturally dried with cherry for rich sweetness and heavy cocoa body. Superb for milk-based espresso drinks, Moka Pot, and South Indian Filter.",
        "taste_notes": ["Dark Chocolate", "Fruit Jam", "Heavy Cocoa", "Molasses"],
        "recommended_brew_methods": ["espresso", "moka_pot", "french_press", "south_indian_filter"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 700.00, "compare_at_price": 650.00, "sku": "HJ-DHAK-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1300.00, "compare_at_price": 1200.00, "sku": "HJ-DHAK-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2380.00, "compare_at_price": 2210.00, "sku": "HJ-DHAK-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/Dhak-Blend-Front.jpg?v=1734947063"}
        ],
        "taste_notes_json": '["Dark Chocolate", "Fruit Jam", "Heavy Cocoa", "Molasses"]',
        "specs_json": '{"Process": "Natural", "Roast": "Dark", "Character": "Heavy Cocoa & Low Acidity"}',
    },
    {
        "id": "prod_silver_oak_cafe_blend",
        "name": "Silver Oak Café Blend",
        "slug": "silver-oak-cafe-blend",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-SILVEROAK-250",
        "category": "blend",
        "price": 750.00,
        "compare_at_price": 700.00,
        "status": "active",
        "in_stock": True,
        "badge": "SIGNATURE HOUSE BLEND",
        "rating": 5.0,
        "review_count": 540,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium",
        "process_method": "washed",
        "estate_name": "Silver Oak Plantations",
        "region": "Karnataka & Tamil Nadu",
        "elevation_m": 1350,
        "varietal": "House Signature Blend",
        "resting_period_days": 8,
        "acidity": "medium",
        "bitterness": "medium",
        "body": "Balanced and Velvety",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/SilverOak-blend-Front.jpg?v=1734957127",
        "description": "The flagship cafe blend poured at Hiljhil roasteries across the country. Named after the shade-providing silver oak trees. Harmonious balance of hazelnut, milk chocolate, and sweet honey.",
        "taste_notes": ["Hazelnut", "Milk Chocolate", "Sweet Honey", "Caramel"],
        "recommended_brew_methods": ["espresso", "aeropress", "pour_over", "cold_brew"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 750.00, "compare_at_price": 700.00, "sku": "HJ-SILVEROAK-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1395.00, "compare_at_price": 1300.00, "sku": "HJ-SILVEROAK-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2550.00, "compare_at_price": 2380.00, "sku": "HJ-SILVEROAK-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/SilverOak-blend-Front.jpg?v=1734957127"}
        ],
        "taste_notes_json": '["Hazelnut", "Milk Chocolate", "Sweet Honey", "Caramel"]',
        "specs_json": '{"Profile": "Flagship House Blend", "Roast": "Medium", "Body": "Velvety Crema"}',
    },
    {
        "id": "prod_amaltas_blend",
        "name": "Amaltas Blend",
        "slug": "amaltas-blend",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-AMALTAS-250",
        "category": "blend",
        "price": 700.00,
        "compare_at_price": 650.00,
        "status": "active",
        "in_stock": True,
        "badge": "LIGHT & FRUITY",
        "rating": 4.9,
        "review_count": 180,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "light",
        "process_method": "washed",
        "estate_name": "Kerala & Tamil Nadu Blend",
        "region": "Kerala & Tamil Nadu",
        "elevation_m": 1300,
        "varietal": "Washed & Natural Arabica",
        "resting_period_days": 16,
        "acidity": "medium-high",
        "bitterness": "low",
        "body": "Crisp and Refreshing",
        "best_enjoyed": "black",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/Amaltas-Blend-Front.jpg?v=1735023810",
        "description": "Celebration of the golden Indian summer tree. Combination of washed and natural lots roasted light for refreshing notes of ripe blueberry, sweet citrus, and milk chocolate finish.",
        "taste_notes": ["Blueberry", "Milk Chocolate", "Sweet Citrus", "Floral"],
        "recommended_brew_methods": ["pour_over", "aeropress", "cold_brew"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 700.00, "compare_at_price": 650.00, "sku": "HJ-AMALTAS-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1300.00, "compare_at_price": 1200.00, "sku": "HJ-AMALTAS-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2380.00, "compare_at_price": 2210.00, "sku": "HJ-AMALTAS-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/Amaltas-Blend-Front.jpg?v=1735023810"}
        ],
        "taste_notes_json": '["Blueberry", "Milk Chocolate", "Sweet Citrus", "Floral"]',
        "specs_json": '{"Profile": "Bright & Fruity", "Roast": "Light", "BestFor": "Iced Pour Over & Cold Brew"}',
    },
    {
        "id": "prod_cold_brew_blend_bold",
        "name": "Cold Brew Blend Bold",
        "slug": "cold-brew-blend-bold",
        "brand": "Hiljhil Roasters",
        "sku": "HJ-COLDBREW-BOLD-250",
        "category": "blend",
        "price": 700.00,
        "compare_at_price": 650.00,
        "status": "active",
        "in_stock": True,
        "badge": "COLD BREW FAVORITE",
        "rating": 5.0,
        "review_count": 290,
        "tax_category": "coffee_beans",
        "width_cm": 12.0,
        "height_cm": 20.0,
        "depth_cm": 6.0,
        "weight_kg": 0.25,
        "top_clearance_cm": 0.0,
        "side_clearance_cm": 0.0,
        "rear_clearance_cm": 0.0,
        "roast_level": "medium_dark",
        "process_method": "washed",
        "estate_name": "Karnataka Blend",
        "region": "Karnataka",
        "elevation_m": 1200,
        "varietal": "Arabica Washed",
        "resting_period_days": 11,
        "acidity": "low",
        "bitterness": "medium-high",
        "body": "Full-Bodied and Bold",
        "best_enjoyed": "both",
        "image_url": "https://cdn.shopify.com/s/files/1/0738/1409/files/Cold-Brew-Blend-Bold-Front.jpg?v=1735024000",
        "description": "Engineered for deep steep extraction. Low acidity, high sweetness, and heavy body. Delivers chocolate-thick iced glasses with roasted nut aromas and bittersweet finish.",
        "taste_notes": ["Dark Chocolate", "Toffee", "Roasted Nuts", "Bittersweet Finish"],
        "recommended_brew_methods": ["cold_brew", "french_press", "moka_pot"],
        "variants": [
            {"size": "250g", "weight_grams": 250, "price": 700.00, "compare_at_price": 650.00, "sku": "HJ-COLDBREW-BOLD-250", "available": True},
            {"size": "500g", "weight_grams": 500, "price": 1300.00, "compare_at_price": 1200.00, "sku": "HJ-COLDBREW-BOLD-500", "available": True},
            {"size": "1kg", "weight_grams": 1000, "price": 2380.00, "compare_at_price": 2210.00, "sku": "HJ-COLDBREW-BOLD-1KG", "available": True},
        ],
        "images": [
            {"position": 1, "src": "https://cdn.shopify.com/s/files/1/0738/1409/files/Cold-Brew-Blend-Bold-Front.jpg?v=1735024000"}
        ],
        "taste_notes_json": '["Dark Chocolate", "Toffee", "Roasted Nuts", "Bittersweet Finish"]',
        "specs_json": '{"SteepTime": "16-18 Hours", "Roast": "Medium-Dark", "Acidity": "Low"}',
    },
    {
        "id": "prod_breville_barista_touch",
        "name": "Barista Touch Espresso Machine",
        "slug": "breville-barista-touch",
        "brand": "Breville",
        "sku": "BES880BSS",
        "category": "espresso_machine",
        "price": 999.95,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "BESTSELLER",
        "rating": 5.0,
        "review_count": 142,
        "tax_category": "equipment",
        "width_cm": 32.2,
        "height_cm": 40.7,
        "depth_cm": 32.2,
        "weight_kg": 10.3,
        "top_clearance_cm": 12.0,
        "side_clearance_cm": 5.0,
        "rear_clearance_cm": 5.0,
        "image_url": "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=600&auto=format&fit=crop&q=80",
        "cutout_url": "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=600&auto=format&fit=crop&q=80",
        "description": "Automated touchscreen espresso machine with integrated precision grinder and automated microfoam milk texturing.",
        "specs_json": '{"Power": "1680 Watts", "Pump": "15 Bar Italian Pump", "Heating": "ThermoJet 3-second heat up"}',
    },
    {
        "id": "prod_fellow_ode_gen2",
        "name": "Fellow Ode Gen 2 Brew Grinder",
        "slug": "fellow-ode-gen2",
        "brand": "Fellow",
        "sku": "FEL-ODE-G2-BLK",
        "category": "grinder",
        "price": 345.00,
        "compare_at_price": None,
        "status": "active",
        "in_stock": True,
        "badge": "PRO GEAR",
        "rating": 4.9,
        "review_count": 84,
        "tax_category": "equipment",
        "width_cm": 12.0,
        "height_cm": 24.1,
        "depth_cm": 23.9,
        "weight_kg": 4.5,
        "top_clearance_cm": 4.0,
        "side_clearance_cm": 2.0,
        "rear_clearance_cm": 2.0,
        "image_url": "https://images.unsplash.com/photo-1589396575653-c09c794ff6a6?w=800&auto=format&fit=crop&q=80",
        "description": "Engineered for pour-over and drip brewing with commercial-grade 64mm flat burrs, anti-static technology, and single-dose zero-retention loading.",
        "specs_json": '{"Burrs": "64mm stainless steel flat burrs", "Capacity": "100g single-dose load"}',
    },
]


async def seed_database(session: AsyncSession):
    inserted = 0
    updated = 0
    for item in SEED_PRODUCTS:
        result = await session.execute(select(Product).where(Product.id == item["id"]))
        existing = result.scalars().first()
        if existing is None:
            prod = Product(**item)
            session.add(prod)
            inserted += 1
        else:
            for k, v in item.items():
                setattr(existing, k, v)
            updated += 1
    await session.commit()
    print(f"Catalog seeding complete: {inserted} inserted, {updated} updated.")


async def main():
    async with AsyncSessionLocal() as session:
        await seed_database(session)
    from src.db.database import engine
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
