import json
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field, model_validator


class ClearanceRules(BaseModel):
    top_clearance_cm: float = Field(0.0, description="Required vertical clearance for lids/steam/ventilation")
    side_clearance_cm: float = Field(0.0, description="Required side clearance for ventilation/access")
    rear_clearance_cm: float = Field(0.0, description="Required rear clearance for airflow/cables")


class PhysicalDimensions(BaseModel):
    width_cm: float = Field(..., description="Product physical width in cm")
    height_cm: float = Field(..., description="Product physical height in cm")
    depth_cm: float = Field(..., description="Product physical depth in cm")
    weight_kg: Optional[float] = Field(None, description="Product weight in kg")


class ProductVariantItem(BaseModel):
    id: Optional[str] = None
    size: str  # e.g. '250g', '500g', '1kg'
    weight_grams: int = 250
    price: float
    compare_at_price: Optional[float] = None
    available: bool = True
    sku: Optional[str] = None
    dimensions_cm: Optional[dict[str, float]] = None


class ProductBase(BaseModel):
    name: str
    slug: Optional[str] = None
    brand: str = "Hiljhil Roasters"
    sku: Optional[str] = Field(None, description="Stock Keeping Unit (auto-generated by API if omitted)")
    category: str
    price: float
    compare_at_price: Optional[float] = None
    status: str = Field("active", description="'active', 'draft', or 'archived'")
    in_stock: bool = Field(True, description="Whether the product is available to purchase")
    badge: Optional[str] = None
    rating: float = 5.0
    review_count: int = 0
    tax_category: str = Field("coffee_beans", description="Tax classification code")

    # Dimensions & Clearances
    width_cm: float = 12.0
    height_cm: float = 20.0
    depth_cm: float = 6.0
    weight_kg: Optional[float] = 0.25
    top_clearance_cm: float = 0.0
    side_clearance_cm: float = 0.0
    rear_clearance_cm: float = 0.0

    # Specialty Coffee Terroir & Craft
    roast_level: Optional[str] = None  # light, medium, medium_dark, dark
    process_method: Optional[str] = None  # washed, natural, anaerobic, etc.
    estate_name: Optional[str] = None
    region: Optional[str] = None
    elevation_m: Optional[int] = None
    varietal: Optional[str] = None
    resting_period_days: Optional[int] = None
    acidity: Optional[str] = None
    bitterness: Optional[str] = None
    body: Optional[str] = None
    best_enjoyed: Optional[str] = None

    # Assets & Descriptions
    image_url: Optional[str] = None
    cutout_url: Optional[str] = None
    description: Optional[str] = None

    # JSONB Collections
    taste_notes: Optional[list[str]] = None
    recommended_brew_methods: Optional[list[str]] = None
    variants: Optional[list[dict[str, Any]]] = None
    images: Optional[list[dict[str, Any]]] = None

    # Legacy compatibility fields
    taste_notes_json: Optional[str] = None
    specs_json: Optional[str] = None


class ProductCreate(ProductBase):
    id: Optional[str] = None

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "name": "Ratnagiri Estate Honey Anaerobic",
                "category": "producer_series",
                "brand": "Hiljhil Roasters",
                "price": 680.0,
                "compare_at_price": 750.0,
                "status": "active",
                "in_stock": True,
                "badge": "LIMITED RELEASE",
                "roast_level": "medium_light",
                "process_method": "honey_anaerobic",
                "estate_name": "Ratnagiri Estate",
                "region": "Bababudangiri, Karnataka",
                "elevation_m": 1400,
                "varietal": "Catuai",
                "resting_period_days": 14,
                "acidity": "medium_high",
                "bitterness": "low",
                "body": "Silky",
                "best_enjoyed": "black",
                "description": "Fermented with natural coffee cherry honey in temperature-controlled tanks for 72 hours, delivering intense floral jasmine and stone fruit sweetness.",
                "taste_notes": ["Jasmine", "Peach", "Honey", "Blood Orange"],
                "recommended_brew_methods": ["pour_over", "aeropress"],
                "variants": [
                    {"size": "250g", "price": 680.0, "weight_grams": 250, "available": True},
                    {"size": "500g", "price": 1280.0, "weight_grams": 500, "available": True}
                ],
                "width_cm": 12.0,
                "height_cm": 20.0,
                "depth_cm": 6.0,
                "weight_kg": 0.25
            }
        }
    )


class ProductUpdate(BaseModel):
    name: Optional[str] = None
    slug: Optional[str] = None
    brand: Optional[str] = None
    sku: Optional[str] = None
    category: Optional[str] = None
    price: Optional[float] = None
    compare_at_price: Optional[float] = None
    status: Optional[str] = None
    in_stock: Optional[bool] = None
    badge: Optional[str] = None
    rating: Optional[float] = None
    review_count: Optional[int] = None
    tax_category: Optional[str] = None

    width_cm: Optional[float] = None
    height_cm: Optional[float] = None
    depth_cm: Optional[float] = None
    weight_kg: Optional[float] = None
    top_clearance_cm: Optional[float] = None
    side_clearance_cm: Optional[float] = None
    rear_clearance_cm: Optional[float] = None

    roast_level: Optional[str] = None
    process_method: Optional[str] = None
    estate_name: Optional[str] = None
    region: Optional[str] = None
    elevation_m: Optional[int] = None
    varietal: Optional[str] = None
    resting_period_days: Optional[int] = None
    acidity: Optional[str] = None
    bitterness: Optional[str] = None
    body: Optional[str] = None
    best_enjoyed: Optional[str] = None

    image_url: Optional[str] = None
    cutout_url: Optional[str] = None
    description: Optional[str] = None

    taste_notes: Optional[list[str]] = None
    recommended_brew_methods: Optional[list[str]] = None
    variants: Optional[list[dict[str, Any]]] = None
    images: Optional[list[dict[str, Any]]] = None

    taste_notes_json: Optional[str] = None
    specs_json: Optional[str] = None


class ProductResponse(ProductBase):
    id: str

    @model_validator(mode="after")
    def sync_legacy_fields(self):
        # Sync taste_notes list into taste_notes_json if empty
        if not self.taste_notes_json and self.taste_notes:
            self.taste_notes_json = json.dumps(self.taste_notes)
        # Or parse taste_notes_json into taste_notes list if empty
        elif not self.taste_notes and self.taste_notes_json:
            try:
                self.taste_notes = json.loads(self.taste_notes_json)
            except Exception:
                pass
        return self

    @property
    def total_required_height_cm(self) -> float:
        return self.height_cm + self.top_clearance_cm

    @property
    def total_required_width_cm(self) -> float:
        return self.width_cm + (2 * self.side_clearance_cm)

    @property
    def total_required_depth_cm(self) -> float:
        return self.depth_cm + self.rear_clearance_cm

    model_config = ConfigDict(from_attributes=True)


class ProductListResponse(BaseModel):
    total: int
    items: list[ProductResponse]


class DimensionSearchQuery(BaseModel):
    max_height_cm: Optional[float] = None
    max_width_cm: Optional[float] = None
    max_depth_cm: Optional[float] = None
    category: Optional[str] = None
    limit: int = 10


class CatalogFacetsResponse(BaseModel):
    categories: list[str] = Field(..., description="List of unique product categories")
    brands: list[str] = Field(..., description="List of unique brand names")
    roast_levels: list[str] = Field(..., description="Available roast profiles")
    process_methods: list[str] = Field(..., description="Available coffee processing methods")
    estates: list[str] = Field(..., description="List of source single-origin coffee estates")
    min_price: float = Field(..., description="Lowest catalog price")
    max_price: float = Field(..., description="Highest catalog price")
    total_products: int = Field(..., description="Total active items in catalog")


class BulkProductCreateRequest(BaseModel):
    products: list[ProductCreate] = Field(..., description="Batch list of products to create or sync")


class BulkProductResponse(BaseModel):
    inserted: int = Field(..., description="Number of new products inserted")
    updated: int = Field(..., description="Number of existing products updated")
    total: int = Field(..., description="Total products processed")

